services:
- type: web
  name: nuntx-law-backend
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  autoDeploy: false
  envVars:
  - key: SECRET_KEY
    generateValue: true
  - key: SQLALCHEMY_DATABASE_URI
    value: postgresql+psycopg://USER:PASSWORD@HOST:5432/DBNAME
  - key: FRONTEND_ORIGIN
    value: https://example.netlify.app
